services:
  odoo-backend:
    build: ./odoo
    container_name: odoo-backend-api-services
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./odoo
        target: /app/odoo

volumes:
  odoo-server: